version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    volumes:
      - .m2:/root/.m2

networks:
  springapimysql-net:
